export const API_ENDPOINTS = {
  users: "/users",
  userById: (id: string) => `/users/${id}`,

  meeting: "/meetings",
  meetingById: (id: string) => `/meetings/${id}`,
  myMeetings: "/meetings/my",
  joinByCode: (joinCode: string) => `/meetings/join/${joinCode}`,
  cancelMeeting: (id: string) => `/meetings/${id}/cancel`,
  endMeeting: (id: string) => `/meetings/${id}/end`,
  meetingInvitations: (meetingId: string) => `/meetings/${meetingId}/invitations`,
  myInvitations: "/invitations/my",
  invitationAccept: (id: string) => `/invitations/${id}/accept`,
  invitationDecline: (id: string) => `/invitations/${id}/decline`,
  invitationCancel: (id: string) => `/invitations/${id}/cancel`,
  waitingRoomRequest: (meetingId: string) => `/meetings/${meetingId}/waiting-room/requests`,
  waitingRoomByJoinCode: (joinCode: string) => `/meetings/join/${joinCode}/waiting-room`,
  waitingRoomByInvitation: (invitationId: string) => `/invitations/${invitationId}/waiting-room`,
  myParticipantStatus: (meetingId: string) => `/meetings/${meetingId}/my-status`,
  joinToken: (meetingId: string) => `/meetings/${meetingId}/join-token`,
  leaveMeeting: (meetingId: string) => `/meetings/${meetingId}/leave`,
  waitingRoom: (meetingId: string) => `/meetings/${meetingId}/waiting-room`,
  waitingRoomApprove: (meetingId: string, participantId: string) => `/meetings/${meetingId}/waiting-room/${participantId}/approve`,
  waitingRoomReject: (meetingId: string, participantId: string) => `/meetings/${meetingId}/waiting-room/${participantId}/reject`,
  participants: (meetingId: string) => `/meetings/${meetingId}/participants`,
  removeParticipant: (meetingId: string, participantId: string) => `/meetings/${meetingId}/participants/${participantId}/remove`,
} as const;